#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_JAVA17_HOME="$HOME/.local/jdks/temurin-17"
DEFAULT_ANDROID_SDK_ROOT="$HOME/.local/android-sdk"
DEFAULT_TASK="assembleFdroidDebug"

usage() {
  cat <<'EOF'
Build the Orgzly Revived F-Droid Android flavor.

Usage:
  scripts/build_fdroid.sh [gradle-task] [-- extra gradle args]

Examples:
  scripts/build_fdroid.sh
  scripts/build_fdroid.sh installFdroidDebug
  scripts/build_fdroid.sh assembleFdroidRelease -- --stacktrace
  scripts/build_fdroid.sh bundleFdroidRelease

Environment overrides:
  JAVA17_HOME         Path to the JDK 17 installation to use for Gradle
  ANDROID_SDK_ROOT    Path to the Android SDK
  ANDROID_HOME        Optional alias for ANDROID_SDK_ROOT

Notes:
  - This script forces Gradle to run with Java 17 because this project requires JDK 17.
  - If local.properties is missing, the script creates one pointing at the SDK.
  - assembleFdroidRelease produces an unsigned APK unless you add your own signing config.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

TASK="$DEFAULT_TASK"
if [[ "${1:-}" != "" && "${1:-}" != "--" ]]; then
  TASK="$1"
  shift
fi

EXTRA_ARGS=()
if [[ "${1:-}" == "--" ]]; then
  shift
  EXTRA_ARGS=("$@")
fi

JAVA17_HOME="${JAVA17_HOME:-$DEFAULT_JAVA17_HOME}"
ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$DEFAULT_ANDROID_SDK_ROOT}}"
LOCAL_PROPERTIES="$REPO_ROOT/local.properties"
GRADLEW="$REPO_ROOT/gradlew"

if [[ ! -x "$GRADLEW" ]]; then
  echo "error: gradlew not found at $GRADLEW" >&2
  exit 1
fi

if [[ ! -x "$JAVA17_HOME/bin/java" ]]; then
  cat >&2 <<EOF
error: JDK 17 not found at $JAVA17_HOME
Set JAVA17_HOME to a valid JDK 17 install before running this script.
EOF
  exit 1
fi

if [[ ! -d "$ANDROID_SDK_ROOT" ]]; then
  cat >&2 <<EOF
error: Android SDK not found at $ANDROID_SDK_ROOT
Set ANDROID_SDK_ROOT (or ANDROID_HOME) to a valid SDK path before running this script.
EOF
  exit 1
fi

if [[ ! -f "$LOCAL_PROPERTIES" ]]; then
  cat > "$LOCAL_PROPERTIES" <<EOF
## This file is automatically generated by scripts/build_fdroid.sh for local Android builds.
# Do not commit this file.
sdk.dir=$ANDROID_SDK_ROOT
EOF
  echo "Created $LOCAL_PROPERTIES"
fi

export JAVA_HOME="$JAVA17_HOME"
export PATH="$JAVA_HOME/bin:$PATH"
export ANDROID_SDK_ROOT
export ANDROID_HOME="$ANDROID_SDK_ROOT"

echo "Repo root:        $REPO_ROOT"
echo "Gradle task:      $TASK"
echo "JAVA_HOME:        $JAVA_HOME"
echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"

cd "$REPO_ROOT"
exec "$GRADLEW" "$TASK" "${EXTRA_ARGS[@]}"
