#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_JAVA17_HOME="$HOME/.local/jdks/temurin-17"
DEFAULT_ANDROID_SDK_ROOT="$HOME/.local/android-sdk"
DEFAULT_KEYSTORE="$HOME/orgzly-local-release.jks"
DEFAULT_ALIAS="orgzly-local"
UNSIGNED_APK="$REPO_ROOT/app/build/outputs/apk/fdroid/release/app-fdroid-release-unsigned.apk"
ALIGNED_APK="$REPO_ROOT/app/build/outputs/apk/fdroid/release/orgzly-local-release-aligned.apk"
SIGNED_APK="$REPO_ROOT/app/build/outputs/apk/fdroid/release/orgzly-local-release-signed.apk"
PACKAGE_NAME="com.orgzlyrevived"

usage() {
  cat <<'EOF'
Build, zipalign, sign, verify, and optionally install a local F-Droid release APK.

Usage:
  scripts/build_signed_fdroid_release.sh [options]

Options:
  --install              Install the signed APK with adb after verification.
  --uninstall-first      Uninstall com.orgzlyrevived before installing. Implies --install.
  --skip-build           Skip Gradle build and sign the existing unsigned release APK.
  --ks PATH              Keystore path. Default: ~/orgzly-local-release.jks
  --alias NAME           Key alias. Default: orgzly-local
  --out PATH             Signed APK output path.
  -h, --help             Show this help.

Environment overrides:
  JAVA17_HOME            Path to JDK 17. Default: ~/.local/jdks/temurin-17
  ANDROID_SDK_ROOT       Path to Android SDK. Default: ~/.local/android-sdk
  ANDROID_HOME           Optional alias for ANDROID_SDK_ROOT
  ORGZLY_RELEASE_KS_PASS Keystore password. If unset, apksigner prompts.
  ORGZLY_RELEASE_KEY_PASS Key password. Optional; if unset, apksigner prompts only if needed.

One-time keystore creation example:
  keytool -genkeypair \
    -v \
    -keystore ~/orgzly-local-release.jks \
    -alias orgzly-local \
    -keyalg RSA \
    -keysize 4096 \
    -validity 10000

Notes:
  - This produces a local personal release build, not an F-Droid/App Store submission artifact.
  - Keep the keystore and passwords. Future updates must be signed with the same key.
  - If replacing the official/forked app, uninstall it first because signatures will differ.
EOF
}

INSTALL=false
UNINSTALL_FIRST=false
SKIP_BUILD=false
KEYSTORE="$DEFAULT_KEYSTORE"
KEY_ALIAS="$DEFAULT_ALIAS"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install)
      INSTALL=true
      shift
      ;;
    --uninstall-first)
      INSTALL=true
      UNINSTALL_FIRST=true
      shift
      ;;
    --skip-build)
      SKIP_BUILD=true
      shift
      ;;
    --ks)
      KEYSTORE="${2:-}"
      if [[ -z "$KEYSTORE" ]]; then
        echo "error: --ks requires a path" >&2
        exit 1
      fi
      shift 2
      ;;
    --alias)
      KEY_ALIAS="${2:-}"
      if [[ -z "$KEY_ALIAS" ]]; then
        echo "error: --alias requires a name" >&2
        exit 1
      fi
      shift 2
      ;;
    --out)
      SIGNED_APK="${2:-}"
      if [[ -z "$SIGNED_APK" ]]; then
        echo "error: --out requires a path" >&2
        exit 1
      fi
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

JAVA17_HOME="${JAVA17_HOME:-$DEFAULT_JAVA17_HOME}"
ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$DEFAULT_ANDROID_SDK_ROOT}}"
LOCAL_PROPERTIES="$REPO_ROOT/local.properties"
GRADLEW="$REPO_ROOT/gradlew"

if [[ ! -x "$GRADLEW" ]]; then
  echo "error: gradlew not found at $GRADLEW" >&2
  exit 1
fi

if [[ ! -x "$JAVA17_HOME/bin/java" ]]; then
  echo "error: JDK 17 not found at $JAVA17_HOME" >&2
  echo "Set JAVA17_HOME to a valid JDK 17 install." >&2
  exit 1
fi

if [[ ! -d "$ANDROID_SDK_ROOT" ]]; then
  echo "error: Android SDK not found at $ANDROID_SDK_ROOT" >&2
  echo "Set ANDROID_SDK_ROOT or ANDROID_HOME to a valid SDK path." >&2
  exit 1
fi

find_build_tool() {
  local tool="$1"
  local direct="$ANDROID_SDK_ROOT/build-tools"
  if [[ ! -d "$direct" ]]; then
    return 1
  fi
  find "$direct" -mindepth 2 -maxdepth 2 -type f -name "$tool" | sort -V | tail -n 1
}

ZIPALIGN="$(find_build_tool zipalign || true)"
APKSIGNER="$(find_build_tool apksigner || true)"

if [[ -z "$ZIPALIGN" || ! -x "$ZIPALIGN" ]]; then
  echo "error: zipalign not found under $ANDROID_SDK_ROOT/build-tools" >&2
  exit 1
fi

if [[ -z "$APKSIGNER" || ! -x "$APKSIGNER" ]]; then
  echo "error: apksigner not found under $ANDROID_SDK_ROOT/build-tools" >&2
  exit 1
fi

if [[ ! -f "$KEYSTORE" ]]; then
  cat >&2 <<EOF
error: keystore not found at $KEYSTORE
Create one first, for example:

  keytool -genkeypair -v -keystore "$KEYSTORE" -alias "$KEY_ALIAS" -keyalg RSA -keysize 4096 -validity 10000
EOF
  exit 1
fi

if [[ ! -f "$LOCAL_PROPERTIES" ]]; then
  cat > "$LOCAL_PROPERTIES" <<EOF
## This file is automatically generated by scripts/build_signed_fdroid_release.sh for local Android builds.
# Do not commit this file.
sdk.dir=$ANDROID_SDK_ROOT
EOF
  echo "Created $LOCAL_PROPERTIES"
fi

export JAVA_HOME="$JAVA17_HOME"
export PATH="$JAVA_HOME/bin:$PATH"
export ANDROID_SDK_ROOT
export ANDROID_HOME="$ANDROID_SDK_ROOT"

mkdir -p "$(dirname "$SIGNED_APK")"

cat <<EOF
Repo root:        $REPO_ROOT
JAVA_HOME:        $JAVA_HOME
ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
zipalign:         $ZIPALIGN
apksigner:        $APKSIGNER
Keystore:         $KEYSTORE
Key alias:        $KEY_ALIAS
Signed APK:       $SIGNED_APK
Install:          $INSTALL
Uninstall first:  $UNINSTALL_FIRST
EOF

cd "$REPO_ROOT"

if [[ "$SKIP_BUILD" != true ]]; then
  "$GRADLEW" assembleFdroidRelease
fi

if [[ ! -f "$UNSIGNED_APK" ]]; then
  echo "error: unsigned release APK not found at $UNSIGNED_APK" >&2
  exit 1
fi

rm -f "$ALIGNED_APK" "$SIGNED_APK"

"$ZIPALIGN" -p -f 4 "$UNSIGNED_APK" "$ALIGNED_APK"

SIGN_ARGS=(
  sign
  --ks "$KEYSTORE"
  --ks-key-alias "$KEY_ALIAS"
  --out "$SIGNED_APK"
)

if [[ -n "${ORGZLY_RELEASE_KS_PASS:-}" ]]; then
  SIGN_ARGS+=(--ks-pass "pass:$ORGZLY_RELEASE_KS_PASS")
fi

if [[ -n "${ORGZLY_RELEASE_KEY_PASS:-}" ]]; then
  SIGN_ARGS+=(--key-pass "pass:$ORGZLY_RELEASE_KEY_PASS")
fi

SIGN_ARGS+=("$ALIGNED_APK")

"$APKSIGNER" "${SIGN_ARGS[@]}"
"$APKSIGNER" verify --verbose "$SIGNED_APK"

sha256sum "$SIGNED_APK"

if [[ "$INSTALL" == true ]]; then
  if ! command -v adb >/dev/null 2>&1; then
    echo "error: adb not found in PATH" >&2
    exit 1
  fi

  adb devices -l

  if [[ "$UNINSTALL_FIRST" == true ]]; then
    adb uninstall "$PACKAGE_NAME" || true
  fi

  adb install -r "$SIGNED_APK"
fi

cat <<EOF
Done.
Signed APK: $SIGNED_APK
EOF
